### ISSUE TITLE
Thankyou for the interesting work.

### ISSUE THREAD

**Issue by Pranav-chib** [meaten/FlowChain-ICCV2023#2]
Hi author, thanks for such a wonderful paper and the codebase; it is really a great work. On my part, I am not able to reproduce the code's results because of some dependency issues.
![image](https://github.com/meaten/FlowChain-ICCV2023/assets/121541098/6b476233-56e3-4940-93f6-c8d8e0a3da72)
(in src/data/TP/process_data.py)
 If I try to change "from data.TP.environment import Environment, Scene, Node, derivative_of" to "from environment import Environment, Scene, Node, derivative_of", it works fine for the data processing part. However, when training on that data, the code gets stuck.
![image](https://github.com/meaten/FlowChain-ICCV2023/assets/121541098/3479c376-6157-44f4-8a27-06b12452bb8b). 
I have tried to change the sys.path.append, but nothing is working properly. Can you please specify some directions on why this might be happening? 
Thank you for you time.

**Comment by meaten** [comment]
Hi Pranav-chib,

Could you run process_data.py from the root of the workspace as below?
( ~/FlowChain-ICCV2023 ): python src/data/TP/process_data.py

My codes import the modules based on the folder structure starting from the root.

**Comment by Pranav-chib** [comment]
Thank you for the response, yes i have run all the code from the main root directory only (~/FlowChain-ICCV2023). 
The issue is arising due to the ("from data.TP.environment import Environment, Scene, Node, derivative_of"). when i run the precess_data.py it is not picking data.TP.

**Comment by meaten** [comment]
I am glad to hear that you could run all the code.
I will consider packaging my Python modules for convenience and simplicity.

**Comment by mmartaa** [comment]
Hi @meaten, thank you for your amazing work!
I'm trying to replicate your code but I encountered the same problem described in this issue. 

The first time I ran the code, (almost) everything went smoothly and I managed to process the data. However, after that initial successful run, I started getting the error **ModuleNotFound: No module named 'data.TP'**. 
I made sure to run the command (python src/data/TP/process_data.py) from the root of the workspace, just as you suggested, both when it worked and when it didn't. So I'm a bit confused as to why it fails now when nothing has changed in terms of setup or command usage.

I'm trying to use your pipeline with my own trajectory data, and I can't proceed unless the processing step works correctly again.
Do you have any further suggestions on how to resolve this or what might be causing the inconsistency? 

Thank you in advance for you time and support!

**Comment by meaten** [comment]
Hi @mmartaa ,

Sorry for the late reply.
Thanks for using my code.
Does that error occur in `process_data.py` or `main.py`?

**Comment by mmartaa** [comment]
Hi @meaten, thank you for the reply!

It occurred in process_data.py, but I managed to solve it.
Apparently it was due to an error in writing the path with the forward slash (/) instead of the back slash (\). 
Thank you again for the support!
