### ISSUE TITLE
 tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by jsonton** [meaten/FlowChain-ICCV2023#3]
File "E:\code\FlowChain-ICCV2023-main\src\models\TP\mgcvae.py", line 542, in encode_node_history
    return outputs[torch.arange(first_history_indices.shape[0]), last_index_per_sequence]
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by meaten** [comment]
Hi @jsonton,

Thanks for trying my code.
Could you provide more info for error reproduction?
