### ISSUE TITLE
Questions about datas

### ISSUE THREAD

**Issue by wonkicho** [meaten/FlowChain-ICCV2023#5]
Thank you for your awesome works!
during read your code, i wonder that how can i translate my own dataset coordinates to etc/ucy format.
can you give me some advices or information about etc/ucy datasets labels?

thanks!

**Comment by meaten** [comment]
Hi,

Thanks for trying out my code!
I'm working on incorporating _trajdata_ https://github.com/NVlabs/trajdata.
If your target dataset is supported by trajdata, I will soon share the updated version. ( in a few weeks maybe )

Inputs are tensors containing the position/velocity/acceleration info of past trajectories.
Ground truths are tensors containing velocity info of future trajectories.
The calculations of these derivatives are implemented in src/data/TP/process_data.py.
No map information can be used for now, but you can try modifying the Trajectron++ encoder to take it.

If you have any further questions, feel free to tell me.
